version: "3.9"
services:
  hub:
    image: selenium/hub:4.1.2
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.1.2
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - TZ=Asia/Kuala_Lumpur
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
  firefox:
    image: selenium/node-firefox:4.1.2
    shm_size: '2g'   
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
  login-quick-chrome:
    image: candicerm/qsuitest
    depends_on:
      - chrome
    environment:
      - SCHOOL_CODE=seleniumtestschool
      - BROWSER=chrome_r
      - DAILY_TEST=false
      - HUB_HOST=hub
      - MODULE=src/test/resources/uitest/login-quick.xml
    volumes:
      - ./output/login-quick-chrome-result:/usr/share/qsuitest/test-output
  single-chrome:
    image: candicerm/qsuitest
    depends_on:
      - chrome
    environment:
      - SCHOOL_CODE=seleniumtestschool
      - BROWSER=chrome_r
      - DAILY_TEST=false
      - HUB_HOST=hub
      - MODULE=src/test/resources/uitest/test-single.xml
    volumes:
      - ./output/single-firefox-result:/usr/share/qsuitest/test-output
  sis-chrome:
    image: candicerm/qsuitest
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome_r
      - DAILY_TEST=true
      - HUB_HOST=hub
      - MODULE=src/test/resources/uitest/sis.xml
    volumes:
      - ./output/sis-chrome-result:/usr/share/qsuitest/test-output
  oms-chrome:
    image: candicerm/qsuitest
    depends_on:
      - chrome
    environment:
      - SCHOOL_CODE=masterscheduler
      - BROWSER=chrome_r
      - DAILY_TEST=false
      - HUB_HOST=hub
      - MODULE=src/test/resources/uitest/oms.xml
    volumes:
      - ./output/oms-chrome-result:/usr/share/qsuitest/test-output
  smoke-chrome:
    image: candicerm/qsuitest
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome_r
      - DAILY_TEST=true
      - HUB_HOST=hub
      - MODULE=src/test/resources/uitest/test-smoke.xml
    volumes:
      - ./output/smoke-chrome-result:/usr/share/qsuitest/test-output
  printreport-output:
    image: candicerm/printreport
    container_name: printreport
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./:/output/print
      - ../../jobs/QSUITEST_RUNNER/builds/59/archive/output:/output